#!/usr/bin/env ruby

require './coer'

CWD = '%s/.vim/pack' % ENV['HOME']
Dir.chdir CWD

repos = %w[
  rizzatti/dash.vim
  rizzatti/funcoo.vim
  mattn/emmet-vim
  majutsushi/tagbar
  tpope/vim-fugitive
  tpope/vim-rhubarb
  tpope/vim-markdown
  tpope/vim-repeat
  tpope/vim-surround
  tpope/vim-dadbod
  tpope/vim-commentary
  vim-airline/vim-airline
  vim-airline/vim-airline-themes
  fatih/vim-go
  ctrlpvim/ctrlp.vim
  NLKNguyen/papercolor-theme
  AndrewRadev/splitjoin.vim
  elixir-editors/vim-elixir
  chr4/nginx.vim
  nanotech/jellybeans.vim
  vim-ruby/vim-ruby
  jremmen/vim-ripgrep
  hashivim/vim-terraform
  vim-python/python-syntax
  dense-analysis/ale
  airblade/vim-gitgutter
  Vimjas/vim-python-pep8-indent
  morhetz/gruvbox
  vim-test/vim-test
  skywind3000/asyncrun.vim
  tpope/vim-dispatch
  pangloss/vim-javascript
  sainnhe/everforest
  altercation/vim-colors-solarized
  vim-erlang/vim-erlang-tags
  justinmk/vim-dirvish
  kristijanhusak/vim-dirvish-git
  jimenezrick/vimerl
  kristijanhusak/vim-dadbod-completion
  kristijanhusak/vim-dadbod-ui
  vim-scripts/dbext.vim
  preservim/nerdtree
]
coer = Coer.new
coer.enq repos
coer.die

__END__

  # just made things slow
  #
  vim-erlang/vim-erlang-runtime
  vim-erlang/vim-erlang-compiler
  vim-erlang/vim-erlang-omnicomplete

  # not using right now
  #
  tpope/vim-vinegar

  # skipped
  #

  vim-ruby/vim-ruby
  fatih/vim-nginx
  digitaltoad/vim-pug
  neo4j-contrib/cypher-vim-syntax
  slashmili/alchemist.vim
  vim-syntastic/syntastic

  # moved/changed/deprecated
  #

  scrooloose/nerdtree
  scrooloose/syntastic
  bling/vim-airline
  kien/ctrlp.vim
  rking/ag.vim
  mileszs/ack.vim
  vim-scripts/bufkill.vim

  # previously removed
  #

  SirVer/ultisnips
  honza/vim-snippets
  chriskempson/base16-vim
  briancollins/vim-jst
  posva/vim-vue
  hashivim/vim-terraform
  jwalton512/vim-blade
  evidens/vim-twig
