#!/usr/bin/env ruby

CWD = '%s/.vim/pack' % ENV['HOME']
Dir.chdir CWD

class Coer

  COUNT = 4

  def initialize
    @q = Queue.new
    @m = Mutex.new
    @c = ConditionVariable.new

    @ts = Array.new(COUNT).map do
      Thread.new do
        loop do
          msg = @q.pop
          break if msg == :die
          if Array === msg
            co(*msg)
          else
            co(msg)
          end
        end
      end
    end
  end

  def enq a
    a.each {|x| @q.push x }
  end

  def co repo, start = true
    u, r = repo.split('/')
    d = File.join CWD, u, (start ? 'start' : 'opt'), r
    if File.exist? d and File.directory? d
      puts 'updating %s...' % repo
      system 'git pull', chdir: d
    else
      system "git clone https://github.com/#{repo} #{d}", chdir: CWD
    end
    true
  end

  def die
    @ts.length.times { @q.push :die }
    loop do
      Thread.pass
      break if @ts.all? {|t| !t.alive?}
    end
  end

end

repos = %w[
  rizzatti/dash.vim
  rizzatti/funcoo.vim
  mattn/emmet-vim
  majutsushi/tagbar
  tpope/vim-fugitive
  tpope/vim-markdown
  tpope/vim-repeat
  tpope/vim-surround
  tpope/vim-dadbod
  tpope/vim-commentary
  preservim/nerdtree
  vim-syntastic/syntastic
  vim-airline/vim-airline
  fatih/vim-go
  ctrlpvim/ctrlp.vim
  NLKNguyen/papercolor-theme
  mileszs/ack.vim
  AndrewRadev/splitjoin.vim
  elixir-editors/vim-elixir
  chr4/nginx.vim
  vim-scripts/bufkill.vim
]
coer = Coer.new
coer.enq repos
coer.die

__END__

  # skipped
  #

  vim-ruby/vim-ruby
  altercation/vim-colors-solarized
  tpope/vim-rhubarb
  pangloss/vim-javascript
  fatih/vim-nginx
  digitaltoad/vim-pug
  neo4j-contrib/cypher-vim-syntax
  slashmili/alchemist.vim

  # moved/changed/deprecated
  #

  scrooloose/nerdtree
  scrooloose/syntastic
  bling/vim-airline
  kien/ctrlp.vim
  rking/ag.vim

  # previously removed
  #

  SirVer/ultisnips
  honza/vim-snippets
  chriskempson/base16-vim
  briancollins/vim-jst
  posva/vim-vue
  hashivim/vim-terraform
  jwalton512/vim-blade
  evidens/vim-twig
